language: ruby
sudo: false
dist: bionic
arch: ppc64le
include:
- os: linux
  addons:
    packages:
    - build-essential
    - gem
    - make

before_install:
  - sudo apt-get update
  - ./setup_${TRAVIS_OS_NAME}_environment.sh

script:
  - bundle exec rake spec:unit
  - bundle exec rake spec:integration
